version: '2.3'

services:
  scaffold-graph:
    environment:
      - PORT=5000
      - NODE_ENV=production
      - DISCOVERY_ARCHIVE_URL=http://mountebank:5001/archive
      - COMMENTS_URL=http://mountebank:5001/comments
      - EMPLOYEE_API_URL=http://mountebank:5001/employee
      - REACTIONS_URL=http://mountebank:5001/reactions
      - TEST_MODE=true
    build:
      context: .
    command: npm start
    image: scaffold-graph
    container_name: scaffold-graph
    volumes:
      - /node_modules
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "echo", ">", "/dev/tcp/localhost/5000", "||", "exit", "1"]
      interval: 2s
      timeout: 30s
      retries: 10

  scaffold-graph-mountebank:
    build:
      context: .
      dockerfile: Dockerfile.mountebank
    command: npm run start:mountebank
    image: scaffold-graph-mountebank
    container_name: scaffold-graph-mountebank
    ports:
      - "5001:5001"
    healthcheck:
      test: ["CMD", "echo", ">", "/dev/tcp/localhost/5001", "||", "exit", "1"]
      interval: 2s
      timeout: 30s
      retries: 10

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    command: npm test
    image: tests
    container_name: tests
    depends_on:
      scaffold-graph-mountebank:
        condition: service_healthy
      scaffold-graph:
        condition: service_healthy
